# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- prod

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-testLab'
    subscriptionId: '8e07e568-3847-4839-a466-10851c41845f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Lupipa/azureTestLab/prod/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureTestLab'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'